#Database props:
databaseProperties:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://192.168.99.100:5433/statsgen
  username: statsgen
  password: root
  dialect: org.hibernate.dialect.PostgreSQLDialect
  modelPackage: org.yakimovdenis.webserver.models

liquibase:
  enabled: false