dataSource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://192.168.99.100:5432/statsgen
  username: statsgen
  password: root
  dialect: org.hibernate.dialect.PostgreSQLDialect

liquibase:
  enabled: false